import { readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(readFileSync(join(__dirname, "..", "package.json"), "utf8"));

const content = `// Auto-generated by config/generate-version.js — do not edit
export const version = "${pkg.version}";
`;

writeFileSync(join(__dirname, "..", "src", "generated-version.ts"), content);
console.log(`Generated src/generated-version.ts with version ${pkg.version}`);
