# CI for the dist folder
name: CI dist

on:
  pull_request:
    branches:
      - master
    paths:
      - 'dist/**'
      # - '.github/**'
      - 'package.json'
      - 'package-lock.json'
  push:
    branches:
      - master
    paths:
      - 'dist/**'
      # - '.github/**'
      - 'package.json'
      - 'package-lock.json'

jobs:
  test-plebbit-js:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macOS-latest
        node_version:
          # - 14
          - 16

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'npm'

      - run: npm install
      - run: npm run webpack
      - run: npm run test:server & npm run test:server:wait-on
      - run: npm run test:node:parallel
      - run: CHROME_BIN=$(which chrome) FIREFOX_BIN=$(which firefox) npm run test:browser

  test-plebbit-react-hooks:
    uses: ./.github/workflows/CI-dist-plebbit-react-hooks.yml
    secrets: inherit
