# test @plebbit/plebbit-react-hooks repo whichs depends @plebbit/plebbit-js
name: CI plebbit-react-hooks

on:
  workflow_call:

jobs:
  test:
    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write
    runs-on: ubuntu-22.04
    timeout-minutes: 20

    steps:
      - run: sudo apt install -y xvfb
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      # move plebbit-js (working dir) to temp folder
      - run: cp -r . ../plebbit-js-tmp && rm -fr `ls -A1`
      # clone plebbit-react-hooks repo to working dir
      - run: git clone https://github.com/plebbit/plebbit-react-hooks.git .
      # log the current commit for debugging
      - run: git log -n 1
      # move plebbit-js back to working dir in a sub folder
      - run: mv ../plebbit-js-tmp plebbit-js
      # build the latest plebbit-js dist folder
      - run: cd plebbit-js && npm ci
      - run: cd plebbit-js && npm run build
      - run: rm -fr plebbit-js/node_modules
      # install latest plebbit-js using add ./plebbit-js (local folder module)
      - run: yarn remove @plebbit/plebbit-js
      - run: yarn add ./plebbit-js
      - run: rm -rf plebbit-js/yarn.lock
      - run: yarn
      # build
      - run: yarn test --pool=forks
      - run: yarn build
      # disable hosts we shouldn't use
      - run: sudo echo "255.255.255.255 cloudflare-ipfs.com" | sudo tee -a /etc/hosts
      - run: sudo echo "255.255.255.255 pubsubprovider.xyz" | sudo tee -a /etc/hosts
      # installing the browsers shouldn't be needed, but doesn't work without it for some reason
      - run: yarn playwright install
      # test
      - run: DEBUG=plebbit-js:* yarn test:server & yarn test:server:wait-on
      - run: CHROME_BIN=$(which chromium-browser) yarn test:e2e:mock
      - run: DEBUG="plebbit-js:*" CHROME_BIN=$(which chromium-browser) yarn test:e2e:chrome
      - run: DEBUG="plebbit-js:*" FIREFOX_BIN=$(which firefox) yarn test:e2e:firefox
